<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <PublishAot>true</PublishAot>
        <NativeLib>Shared</NativeLib> 
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <InvariantGlobalization>true</InvariantGlobalization>
        <TieredCompilation>false</TieredCompilation>
        <RootNamespace>WhiteBinTools</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.0" />
    </ItemGroup>
    
    <Import Project="..\NativeCommons\NativeCommons.projitems" Label="Shared" />
    
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <PublishAot>true</PublishAot> 
    </PropertyGroup>
</Project>